### ISSUE TITLE
Removing plaintext emails from website

### ISSUE THREAD

**Issue by Nikolaj-K** [JeffreyBool/githubmemory-upptime#14]
Hello JeffreyBool,

I've come across your website because it exposes all git commit email addresses on google search. 
Please avoid publishing this person-id information for web scrapers. I'd say limit it to the usernames.

Thanks and best wishes

----

Example from githubmemory pages:
<img width="681" alt="Bildschirmfoto 2021-03-17 um 17 02 53" src="https://user-images.githubusercontent.com/27020510/111499131-eab12000-8742-11eb-8047-079958e11883.png">

Google:
<img width="847" alt="Bildschirmfoto 2021-03-17 um 17 07 54" src="https://user-images.githubusercontent.com/27020510/111499534-58f5e280-8743-11eb-8a86-13b2f8aa932d.png">

**Comment by JeffreyBool** [comment]
ok

**Comment by Nikolaj-K** [comment]
I'm not 100% sure what "ok" means here, but thanks if you removed it.

Best

**Comment by parangwave** [comment]
Hi, JeffreyBool. 
I've found that all of my git commits and even my old email of GitHub account were searched on google search through githubmemory site like the problem of the screenshot Nikolaj-K posted. Could you remove these kinds of information? 
Thanks.
